<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DecisionsFramework">
      <HintPath>..\..\..\lib\DecisionsFramework.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
